AlarmSystem/Models/AlarmGroup.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AlarmSystem.Models;

public partial class AlarmGroup
{
    public string GroupId { get; set; }

    public string GroupName { get; set; }

    public bool Enable { get; set; }

    public DateTime CreateDate { get; set; }
}

AlarmSystem/Models/AlarmSettings.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace AlarmSystem.Models;

public partial class AlarmSettings
{
    public int Id { get; set; }

    public string Stid { get; set; }

    [DisplayName("API Parameter")]
    public string ParameterColumn { get; set; }

    [DisplayName("欄位名稱")]
    public string ParameterShow { get; set; }

    [DisplayName("閾值")]
    public int Threshold { get; set; }

    [DisplayName("開始時間")]
    public TimeOnly StartTime { get; set; }

    [DisplayName("結束時間")]
    public TimeOnly EndTime { get; set; }

    public DateTime? NextCheckTime { get; set; }
}

AlarmSystem/Models/Js_LineAlarmContext.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace AlarmSystem.Models;

public partial class Js_LineAlarmContext : DbContext
{
    public Js_LineAlarmContext(DbContextOptions<Js_LineAlarmContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AlarmGroup> AlarmGroup { get; set; }

    public virtual DbSet<AlarmItem> AlarmItem { get; set; }

    public virtual DbSet<AlarmSettings> AlarmSettings { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AlarmGroup>(entity =>
        {
            entity.HasKey(e => e.GroupId).HasName("PK_LineGroups");

            entity.Property(e => e.GroupId)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Enable).HasDefaultValue(true);
            entity.Property(e => e.GroupName)
                .HasMaxLength(50)
                .HasDefaultValue("尚未命名");
        });

        modelBuilder.Entity<AlarmItem>(entity =>
        {
            entity.HasKey(e => e.Stid).HasName("PK_AlarmItems");

            entity.Property(e => e.Stid)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.DelayTime).HasDefaultValue(60);
            entity.Property(e => e.Enable).HasDefaultValue(true);
            entity.Property(e => e.GroupId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Location)
                .IsRequired()
                .HasMaxLength(30);
        });

        modelBuilder.Entity<AlarmSettings>(entity =>
        {
            entity.Property(e => e.EndTime).HasPrecision(0);
            entity.Property(e => e.NextCheckTime).HasColumnType("datetime");
            entity.Property(e => e.ParameterColumn)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.ParameterShow)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.StartTime).HasPrecision(0);
            entity.Property(e => e.Stid)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

AlarmSystem/Models/LineGroups.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AlarmSystem.Models;

public partial class LineGroups
{
    public string GroupId { get; set; }

    public string GroupName { get; set; }

    public bool Enable { get; set; }
}

AlarmSystem/ViewModels/AlarmItemViewModel.cs
using AlarmSystem.Dtos;
using AlarmSystem.Models;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace AlarmSystem.ViewModels
{
    public class AlarmItemViewModel
    {
        [Required(ErrorMessage = "編號必填")]
        public string? Stid { get; set; }

        [Required(ErrorMessage ="地點必填")]
        [DisplayName("地點名稱")]
        public string? Location { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "延遲時間必須大於0")]
        [DisplayName("延遲時間(分)")]
        public int DelayTime { get; set; }

        public bool Enable { get; set; }

        public bool BreakAlarm { get; set; }

        public List<AlarmSettings>? Settings { get; set; }
    }
}

AlarmSystem/ViewModels/GroupAlarmListViewModel.cs
namespace AlarmSystem.ViewModels
{
    public class GroupAlarmListViewModel
    {
        public string? GroupId { get; set; }

        public string? GroupName { get; set; }

        public bool Enable { get; set; }

        public DateTime CreateDate { get; set; }

        public ICollection<AlarmItemViewModel>? AlarmItems{ get; set; }

    }
}

AlarmSystem/Views/Shared/Components/GroupAlarmListViewComponent.cs
using AlarmSystem.Services;
using Microsoft.AspNetCore.Mvc;

namespace AlarmSystem.Views.Shared.Components
{
    public class GroupAlarmListViewComponent(GroupService groupService) : ViewComponent
    {
        private readonly GroupService _groupService = groupService;

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var alarms = await  _groupService.GetGroupAlarmList();
            return View(alarms);
        }
    }
}

AlarmSystem/Views/Alarm/CreateEdit.cshtml
@model AlarmSystem.ViewModels.AlarmItemViewModel
@{
    ViewData["Title"] = "Juno Line Alram System";
}

<div class="container-fluid">
    <div class="d-flex justify-content-between">
        <h1 class="display-6 ps-3 fw-bold text-start">編輯 @Model.Stid 警報項目</h1>
        <div>
            @if (Model.Enable)
            {
                <i class="bi bi-circle-fill text-success">上線</i>
            }
            else
            {
                <i class="bi bi-circle-fill text-danger">斷線</i>
            }
        </div>
    </div>
    <div class="alert alert-primary mb-0" role="alert">
        <label>@ViewData["Error"]</label>
        <label>@TempData["Error"]</label>
        <div class="text-danger" asp-validation-summary="All"></div>
    </div>
    <div class="border border-3 border-primary-subtle rounded-3 px-3 my-3">
        <button type="button" class="btn btn-danger p-0 px-2 position-absolute end-0 translate-middle-x m-3" data-bs-toggle="modal" data-bs-target="#Modal_@Model.Stid">
            <i class="bi bi-trash3-fill"></i>
        </button>
        @if (Model.Settings != null)
        {
            <form asp-controller="Alarm" asp-action="CreateEdit" method="post">
                <div class="row align-items-center mt-3">
                    <div class="col-3">
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#Modal_set">
                            <i class="bi bi-plus-lg"></i> 新增項目
                        </button>
                    </div>
                    <input type="hidden" name="Stid" value="@Model.Stid" />
                    <div class="col-2">
                        <label for="location" class="col-form-label" asp-for="@Model.Location"></label>
                        <input type="text" class="form-control" id="location" name="Location" value="@Model.Location">
                    </div>
                    <div class="col-1">
                        <label for="delayTime" class="col-form-label" asp-for="@Model.DelayTime"></label>
                        <input type="number" class="col-2 form-control" id="delayTime" min="1" name="DelayTime" value="@Model.DelayTime">
                    </div>
                    <div class="form-check col-1 mt-4">
                        <input class="form-check-input" type="checkbox" name="BreakAlarm" value="true" id="flexCheckChecked" @(Model.BreakAlarm ? "checked" : "")>
                        <label class="form-check-label" for="flexCheckChecked">
                            斷線通知
                        </label>
                    </div>
                </div>
                @Html.AntiForgeryToken()
                <div class="row row-cols-4 row-cols-lg-5">
                    @for (int i = 0; i < Model.Settings.Count; i++)
                    {
                        <div class="m-3 p-3 border border-3 rounded-3 col position-relative" style="width:360px;">
                            <div class="position-absolute end-0 translate-middle-x">
                                <button type="button" class="btn btn-danger p-0 px-2" data-bs-toggle="modal" data-bs-target="#Modal_@Model.Settings[i].Id">
                                    <i class="bi bi-trash3-fill"></i>
                                </button>
                            </div>
                            <div>
                                <input type="hidden" name="Settings[@i].Stid" value="@Model.Settings[i].Stid">
                            </div>
                            <div>
                                <input type="hidden" name="Settings[@i].Id" value="@Model.Settings[i].Id">
                            </div>
                            <div class="mb-3 col-6">
                                <label for="parameterShow_@i" class="form-label" asp-for="@Model.Settings[i].ParameterShow"></label>
                                <input type="text" class="form-control" id="parameterShow_@i" name="Settings[@i].ParameterShow" value="@Model.Settings[i].ParameterShow">
                            </div>
                            <div class="mb-3 col-6">
                                <label for="parameterColumn_@i" class="form-label" asp-for="@Model.Settings[i].ParameterColumn"></label>
                                <input type="text" class="form-control" id="parameterColumn_@i" name="Settings[@i].ParameterColumn" value="@Model.Settings[i].ParameterColumn">
                            </div>
                            <div class="mb-3">
                                <label for="threshold_@i" class="form-label" asp-for="@Model.Settings[i].Threshold"></label>
                                <input type="number" class="form-control" id="threshold_@i" name="Settings[@i].Threshold" min="1" value="@Model.Settings[i].Threshold">
                            </div>
                            <div class="mb-3 col-6">
                                <label for="startTime_@i" class="form-label" asp-for="@Model.Settings[i].StartTime"></label>
                                <input type="time" class="form-control" id="startTime_@i" name="Settings[@i].StartTime" value="@Model.Settings[i].StartTime.ToString("HH:mm")">
                            </div>
                            <div class="mb-3 col-6">
                                <label for="endTime_@i" class="form-label" asp-for="@Model.Settings[i].EndTime"></label>
                                <input type="time" class="form-control" id="endTime_@i" name="Settings[@i].EndTime" value="@Model.Settings[i].EndTime.ToString("HH:mm")">
                            </div>
                        </div>
                    }
                </div>
                <div class="d-flex justify-content-end mb-3">
                    <button type="submit" class="btn btn-primary me-3">儲存</button>
                    <button class="btn btn-warning" asp-action="Index">返回</button>
                </div>
            </form>
            <!-- Modal 刪除Settings -->
            @foreach (var item in Model.Settings)
            {
                <div class="modal fade" id="Modal_@item.Id" tabindex="-1" aria-labelledby="ModalLabel_@item.Id" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <form asp-controller="Alarm" asp-action="DeleteSet" asp-route-Id="@item.Id" method="post">
                                <div class="modal-header">
                                    <h1 class="modal-title fs-5 text-danger" id="ModalLabel_@item.Id">
                                        <i class="bi bi-exclamation-triangle-fill"></i> 確定要刪除嗎?
                                    </h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    @Html.AntiForgeryToken()
                                    <input type="hidden" name="stid" value="@item.Stid" />
                                    欄位名稱： @item.ParameterShow <br>
                                    欄位： @item.ParameterColumn
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">關閉</button>
                                    <button type="submit" class="btn btn-primary">確定</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
</div>
<!-- Modal 新增Settings -->
<div class="modal fade" id="Modal_set" tabindex="-1" aria-labelledby="ModalLabel_set" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form class="needs-validation" asp-controller="Alarm" asp-action="CreateSettings" method="post" novalidate>
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="ModalLabel_set">
                        新增
                    </h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    @Html.AntiForgeryToken()
                    <div class="row row-cols-1">
                        <div class="col">
                            <div>
                                <input type="hidden" class="form-control" name="Stid" value="@Model.Stid">
                            </div>
                            <div class="mb-3 col-6">
                                <label for="parameterShow" class="form-label">欄位名稱</label>
                                <input type="text" class="form-control" id="parameterShow" name="ParameterShow" value="" required>
                                <div class="invalid-feedback">
                                    欄位必填
                                </div>
                            </div>
                            <div class="mb-3 col-6">
                                <label for="parameterColumn" class="form-label text-danger">API Parameter</label>
                                <input type="text" class="form-control" id="parameterColumn" name="ParameterColumn" value="" required>
                                <div class="invalid-feedback">
                                    欄位必填(且須對應API的Parameter)
                                </div>
                            </div>
                            <div class="mb-3">
                                <label for="threshold" class="form-label">閾值</label>
                                <input type="number" class="form-control" id="threshold" name="Threshold" min="1" value="" required>
                                <div class="invalid-feedback">
                                    閾值必需大於0
                                </div>
                            </div>
                            <div class="mb-3 col-6">
                                <label for="startTime" class="form-label">開始時間</label>
                                <input type="time" class="form-control" id="startTime" name="StartTime" value="00:00">
                            </div>
                            <div class="mb-3 col-6">
                                <label for="endTime" class="form-label">結束時間</label>
                                <input type="time" class="form-control" id="endTime" name="EndTime" value="23:59">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">關閉</button>
                    <button type="submit" class="btn btn-primary">確定</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- Modal 刪除AlarmItem -->
<div class="modal fade" id="Modal_@Model.Stid" tabindex="-1" aria-labelledby="ModalLabel_@Model.Stid" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form asp-controller="Alarm" asp-action="DeleteItem" method="post">
                <div class="modal-header">
                    <h1 class="modal-title fs-5 text-danger" id="ModalLabel_@Model.Stid">
                        <i class="bi bi-exclamation-triangle-fill"></i> 確定要刪除 @Model.Stid 嗎?
                    </h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    @Html.AntiForgeryToken()
                    <input type="hidden" name="stid" value="@Model.Stid" />
                    位置： @Model.Location
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">關閉</button>
                    <button type="submit" class="btn btn-primary">確定</button>
                </div>
            </form>
        </div>
    </div>
</div>

AlarmSystem/Views/Shared/Components/GroupAlarmList/Default.cshtml
@model IEnumerable<AlarmSystem.ViewModels.GroupAlarmListViewModel>

<li>
    <a asp-controller="Alarm" asp-action="Index" class="btn text-secondary border-0" type="button">
        <i class="bi bi-stars"></i>
        警報群組
    </a>
</li>
@foreach (var group in Model)
{
    <li>
        <button class="btn text-secondary border-0" type="button" data-bs-toggle="collapse" data-bs-target="#collapse_@group.GroupId" aria-expanded="false" aria-controls="collapse_@group.GroupId">
            <i class="bi bi-star-fill"></i>
            @if (group.GroupName == null)
            {
                @group.CreateDate
            }
            else
            {
                @group.GroupName
            }
            <i class="bi bi-caret-right-fill"></i>
        </button>
        <div class="collapse px-3" id="collapse_@group.GroupId">
            <div class="card card-body p-0">
                <ul class="list-unstyled">
                    @foreach (var alarm in group.AlarmItems!)
                    {
                        <li class="border border-1 rounded-1">
                            <a class="btn btn-primary border-0 d-block d-flex justify-content-between" asp-controller="Alarm" asp-action="CreateEdit" asp-route-stid="@alarm.Stid">
                                <span>@alarm.Stid</span>
                                @if (alarm.Enable)
                                {
                                    <i class="bi bi-circle-fill text-success"></i>
                                }
                                else
                                {
                                    <i class="bi bi-circle-fill text-danger"></i>
                                }
                            </a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </li>
}

AlarmSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="icon" href="~/favicon.ico" type="image/x-icon" />
    <link href="~/lib/perfect-scrollbar/css/perfect-scrollbar.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/all.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body class="bg-secondary">
    <div class="d-flex">
        <div id="sidebars" class="d-flex flex-column flex-shrink-0 p-3 text-bg-primary px-0 fixed-start" style="width: 280px;">
            <a class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none ps-3" asp-controller="Alarm" asp-action="Index">
                <img class="mb-1" src="~/favicon.ico" alt="js" />
                <span class="fs-4 ps-2">警報系統</span>
            </a>
            <hr>
            <ul id="container" class="list-unstyled mb-auto overflow-hidden">
                @await Component.InvokeAsync("GroupAlarmList")
            </ul>
        </div>
        <div id="content" class="flex-grow-1" style="margin-left:280px;">
            <main role="main" class="d-flex flex-column justify-content-between">
                <div class="mb-3">
                    <header>
                        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                            <div class="container-fluid">
                                <button id="listBtn" class="btn btn-primary py-1">
                                    <i class="bi bi-list" style="font-size:20px;"></i>
                                </button>
                                @* <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                                <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                                </li>
                                </ul>
                                </div> *@
                                <div class="dropdown">
                                    <a href="#" class="d-flex align-items-center text-primary text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                        <img src="~/img/default.jpg" alt="" width="32" height="32" class="rounded-circle me-2">
                                        <strong>yanwei</strong>
                                    </a>
                                    <ul class="dropdown-menu dropdown-menu-dark text-small shadow" style="right:0;left:auto;">
                                        <li><a class="dropdown-item" href="#">個人資訊</a></li>
                                        <li><hr class="dropdown-divider"></li>
                                        <li><a class="dropdown-item" href="#">登出</a></li>
                                    </ul>
                                </div>
                            </div>
                        </nav>
                    </header>
                    @RenderBody()
                </div>
                <footer class="border-top footer text-muted fixed-bottom z-0">
                    <div class="container">
                        &copy; 2024 - JseneAlarmSystem
                    </div>
                </footer>
            </main>
        </div>
    </div>
    <script src="~/lib/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>